# Generated by Django 3.2.10 on 2021-12-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korzinkamodel',
            name='total',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
