# Generated by Django 3.2.10 on 2021-12-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_auto_20211225_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzinkamodel',
            name='soni',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='korzinkamodel',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
