# Generated by Django 3.2.10 on 2021-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_auto_20211225_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='zapas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
