# Generated by Django 3.2.9 on 2022-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_alter_korzinkamodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='korzinkamodel',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='korzinkamodel',
            name='telefon',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='korzinkamodel',
            name='user_p',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='korzinkamodel',
            name='is_deliver',
            field=models.BooleanField(default=False),
        ),
    ]
